services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=TODOLIST_DB'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_ROOT_HOST=%'
#      - 'MYSQL_USER=todolist'
#      - 'MYSQL_PASSWORD=1234'
      - 'TZ=Asia/Seoul'
    ports:
      - 33061:3306
    networks:
      - default
  redis:
    image: 'redis:latest'
    ports:
      - 63791:6379